ProVis.config = {
  allowInplaceEdit: true,
  allowSplitLinks: true,
  allowUnanchoredLinks: true,
  anchorInColor: '#0f0',
  anchorOutColor: '#f00',
  captionBackground: '#eee',
  captionFontSize: 14,
  captionForeground: '#555',
  captionGradientAngle: 90,
  captionGradientColor: '#fff',
  captionHeight: 40,
  captionUseGradient: true,
  defaultBehavior: 3,
  defaultHandleStyle: 5,
  defaultHandleSize: 8,
  gridSizeX: 15,
  gridSizeY: 15,
  gridStyle: 1,
  hideDisabledHandles: true,
  linkCascadeOrientation: 2,
  linkEndsMovable: true,
  linkPenSize: 1.25,
  linkPenColor: '#333',
  linksSnapToBorders: true,
  linkStyle: 2,
  showAnchors: 2,
  showGrid: true,
  snapToAnchor: 1,
  swimlaneBackBrush: '#fff',
  swimlaneHandles: 0,
  swimlaneHeight: 500,
  swimlaneTopHandles: 32 + 256,
  swimlaneWidth: 150,
  undoCommandHistory: 25,
  zoomStep: 25
};
